# Vehicle Params
wheelbase: 0.3302 # meters
width: 0.2032 # meters
max_steering_angle: 0.4189 # radians

# VESC Params
speed_to_erpm_gain: 4614
speed_to_erpm_offset: 0
steering_angle_to_servo_gain: -1.2135
steering_angle_to_servo_offset: 0.5

# Topics
odom_topic: odom

drive_mode_topic: drive_mode

joy_drive_topic: ackermann_joy
auto_drive_topic: ackermann_auto
selected_drive_topic: ackermann_selected
safe_drive_topic: ackermann_cmd

time_to_collision_topic: ttc