# The distance between the front and
# rear axle of the racecar
wheelbase: 0.3302 # meters
# width of racecar
width: 0.2032 # meters

# steering delay
buffer_length: 5

# Limits on the speed and steering angle
max_speed: 7. #  meters/second
max_steering_angle: 0.4189 # radians
max_accel: 7.51 # meters/second^2
max_decel: 8.26 # meters/second^2
max_steering_vel: 3.2 # radians/second
friction_coeff: 0.523 # - (complete estimate)
height_cg: 0.074 # m (roughly measured to be 3.25 in)
l_cg2rear: 0.17145 # m (decently measured to be 6.75 in)
l_cg2front: 0.15875 # m (decently measured to be 6.25 in)
C_S_front: 4.718 #.79 # 1/rad ? (estimated weight/4)
C_S_rear: 5.4562 #.79 # 1/rad ? (estimated weight/4)
mass: 3.47 # kg (measured on car 'lidart')
moment_inertia: .04712 # kg m^2 (estimated as a rectangle with width and height of car and evenly distributed mass, then shifted to account for center of mass location)

# The rate at which the pose and the lidar publish
update_pose_rate: 0.001

# Lidar simulation parameters
scan_beams: 1080
scan_field_of_view: 6.2831853 #4.71 # radians

# The distance from the center of the
# rear axis (base_link) to the lidar
scan_distance_to_base_link: 0.275 # meters

# The standard deviation of the noise applied
# to the lidar simulation
scan_std_dev: 0.01 # meters

# The probability threshold for points
# in the occupancy grid to be considered "free".
# Used for the lidar simulator.
map_free_threshold: 0.8

# obstacle parameters
obstacle_size: 2

# The names of topics to listen and publish to
joy_topic: "/joy"
drive_topic: "/drive"
map_topic: "/map"
scan_topic: "/scan"
pose_topic: "/pose"
ground_truth_pose_topic: "/gt_pose"
odom_topic: "/odom"
imu_topic: "/imu"
pose_rviz_topic: "/initialpose"

# The names of the transformation frames published to
map_frame: "odom"
base_frame: "base_link"
scan_frame: "laser"

broadcast_transform: true
publish_ground_truth_pose: true
